image: node:22.2.0-alpine

stages:
  - build
  - deploy

variables:
  NODE_ENV: $NODE_ENV

# variables:
#   SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
#   SERVER: $SERVER
#   USER: $USER

# before_script:
#   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
#   - eval $(ssh-agent -s)
#   - echo "$SSH_PRIVATE_KEY" | ssh-add -

build:
  stage: build
  script:
    - echo "Building Next.js app"
    - echo ["${CI_COMMIT_REF_NAME}"]
    - echo "NODE_ENV is ${NODE_ENV}"
    # - if [ "${CI_COMMIT_REF_NAME}" != "main" ]; then export NEXT_PUBLIC_ISDEV=true; fi
    # - env | grep -e ACS_PRIVATE_KEY -e ACS_PUBLIC_KEY -e APPILY_API_KEY -e APPILY_API_URL -e PARTNER_EXTERNAL_ID -e PROGRAM_EXTERNAL_ID -e NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID -e NEXT_PUBLIC_ISDEV >> .env.production
    - echo "NEXT_PUBLIC_ISDEV is ${NEXT_PUBLIC_ISDEV}"
    - npm install
    - npm run build
  artifacts:
    paths:
      - .next/

deploy:
  stage: deploy
  only:
    - tags
  script:
    - echo "Deploying to production server..."
