name: QA/Staging Deploy via SST to AWS

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for deployment"
        required: false
        default: "No reason provided"
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "*.json"
      - "*.yaml"
      - "*.json"
      - "*.config.js"
      - "*.config.ts"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Staging
    env:
      NEXT_PUBLIC_APP_URL: ${{ vars.NEXT_PUBLIC_APP_URL}}
      NEXT_PUBLIC_CMS_URL: ${{ vars.NEXT_PUBLIC_CMS_URL}}
      NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID: ${{ vars.NEXT_PUBLIC_GTAG_ID}}
      NEXT_PUBLIC_GTAG_ID: ${{ vars.NEXT_PUBLIC_GTAG_ID}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache Next.js Build
        uses: actions/cache@v4
        with:
          path: |
            .next/cache/
            .open-next/
            .sst/
          key: cache-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]xs') }}
          restore-keys: |
            cache-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - name: Install Pnpm
        run: npm install -g pnpm

      - name: Install projects deps
        run: pnpm install

      - name: Install AWS Creds
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Set SST Config Secret
        run: |
          npx sst secret set COMMIT_SHA '${{ github.sha }}' --stage staging

      - name: Deploy to AWS with SST
        run: pnpm run deploy:staging

      - name: Clean Up AWS Profile
        run: |
          rm -rf ~/.aws

      - name: Create Pull Request to Production
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REASON="${{ github.event.inputs.reason || 'No reason provided' }}"
          ACTOR="${{ github.actor }}"
          DATE=$(date)
          gh pr create --base production --head main --title "Auto- Deploy by $ACTOR on $DATE" --body "Reason: $REASON"
